# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=80)),
                ('descripcion', models.TextField(max_length=250)),
                ('fechaPublicacion', models.PositiveIntegerField(max_length=4)),
                ('pais', models.CharField(max_length=15)),
                ('portada', models.ImageField(upload_to='portadas/')),
                ('video', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('puesto', models.CharField(max_length=20)),
                ('institucion', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=15)),
                ('cv', models.URLField()),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('edicion', models.TextField()),
                ('anoPublicacion', models.PositiveSmallIntegerField(max_length=4)),
                ('portada', models.ImageField(upload_to='portadas/')),
            ],
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTematica', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='autores',
            field=models.ManyToManyField(to='home.Autor'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Evento'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Libro'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='tematica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tematica'),
        ),
    ]
