# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='fechaPublicacion',
            new_name='anoPublicacion',
        ),
    ]
