# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170130_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='articulo',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Pais'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='autor',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Pais'),
        ),
    ]
