# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170131_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='descarga',
            field=models.URLField(default='www.descarga.org'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='video',
            field=models.URLField(default='www.youtube.com'),
        ),
    ]
