# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170131_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=140),
        ),
    ]
