# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170131_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='pais',
            new_name='paisResidencia',
        ),
        migrations.AddField(
            model_name='articulo',
            name='issuu',
            field=models.TextField(default='blank', max_length=100),
        ),
        migrations.AddField(
            model_name='autor',
            name='tematicas',
            field=models.ManyToManyField(to='home.Tematica'),
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='pais',
        ),
        migrations.AddField(
            model_name='articulo',
            name='pais',
            field=models.ManyToManyField(to='home.Pais'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='autor',
            name='institucion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='autor',
            name='puesto',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='pais',
            name='pais',
            field=models.CharField(max_length=15),
        ),
    ]
