# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170201_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(max_length=250)),
                ('anoPublicacion', models.PositiveIntegerField(max_length=4)),
                ('issuu', models.TextField(default='blank', max_length=100)),
                ('portada', models.ImageField(upload_to='portadas/')),
                ('descarga', models.URLField(default='www.descarga.org')),
                ('video', models.URLField(default='www.youtube.com')),
                ('autores', models.ManyToManyField(to='home.Autor')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Evento')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Libro')),
                ('pais', models.ManyToManyField(to='home.Pais')),
                ('tematica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tematica')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_material', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='autores',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='tematica',
        ),
        migrations.DeleteModel(
            name='Articulo',
        ),
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Tipo'),
        ),
    ]
