# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170201_1449'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tipo',
            new_name='Clasificacion',
        ),
        migrations.RenameModel(
            old_name='Material',
            new_name='Contenido',
        ),
        migrations.RenameField(
            model_name='clasificacion',
            old_name='tipo_de_material',
            new_name='tipo_de_contenido',
        ),
    ]
