# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170201_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='issuu',
            field=models.TextField(default='codigo para insertar issuu (Embeded)', max_length=250),
        ),
        migrations.AlterField(
            model_name='libro',
            name='edicion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=250),
        ),
    ]
