# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170206_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='nombreCortoURL',
            field=models.CharField(default='las palabras deber ir separadas por guiones bajos', max_length=80),
        ),
    ]
