# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20170214_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='nombreCortoURL',
        ),
        migrations.AddField(
            model_name='contenido',
            name='slug',
            field=models.SlugField(default='texto-separado-por-guiones', max_length=100),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
