# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20170214_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='slug',
            field=models.SlugField(default='texto-separado-por-guiones', max_length=80),
        ),
    ]
