# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20170217_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='tematica',
            name='slug',
            field=models.SlugField(default='nombre-separado-por-guiones', max_length=80),
        ),
    ]
