# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20170222_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tematica',
            name='slugTematica',
        ),
        migrations.AlterField(
            model_name='contenido',
            name='descripcion',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
