# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20170228_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='descripcion',
            field=models.TextField(blank=True, max_length=350),
        ),
    ]
