# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-03 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_contenido_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='destacar',
            field=models.BooleanField(default=False),
        ),
    ]
