# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-05 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20171003_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='tematica',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
