# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20171022_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='cv',
            field=models.URLField(default='http://www.redue-alcue.org'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Articulo'), (1, 'Presentaci\xf3n'), (2, 'Libro')], default=0),
        ),
    ]
